[package]
name = "restaurant"
version = "0.1.0"
authors = ["Aijaz A. Ansari <aijaz@aijaz.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
